### ISSUE TITLE
Is there anything to stop a timeline being served up as an embed to another site?

### ISSUE THREAD

**Issue by paul-hammant** [thecdil/timelinejs-template#12]
There's a raw URL like so - https://raw.githubusercontent.com/thecdil/timelinejs-template/main/media/example-timeline.json

There's also the served up resource from the site in-situ - https://thecdil.github.io/timelinejs-template/media/example-timeline.json

What of the rest of the JavaScript and CSS can be used in an embed way to get a timeline to appear elsewhere on the web?  And of course it may require an iframe to get it working.

Thoughts?

**Comment by evanwill** [comment]
Yes, I designed the `embed` layout to enable you to generate+host your timeline on gh-pages, but embed as iframe somewhere else--its not really well doc-ed yet, but see layouts section in https://github.com/thecdil/timelinejs-template/blob/main/docs/timeline.md 

Basically, on your timeline page, change the layout to embed in front matter, 

```
---
title: A Great Timeline
layout: embed
# add TimelineJS
timeline: demo-timeline
---
```

The timeline "page" will be generated without any nav or template elements, it is just the timeline itself (meaning you also probably don't want it in the nav, thus left out the `nav` option in front matter).

Then on the other site where you want to embed it, add an iframe with src being the link to the page, e.g. 

```
<iframe src="https://thecdil.github.io/timelinejs-template/example.html" width='600' height='600' frameborder='0'></iframe>
```

(basically just like you would do with a Knightlab hosted version)

I will add an example and doc at some point.

**Comment by paul-hammant** [comment]
Yeah, I'm feeling stupid right now as I'd gazed at the embed layout previously and wondered what that was for. D'oh!!

**Comment by evanwill** [comment]
ha ha, just quickly added note in the docs and an example, try
`<iframe src="https://thecdil.github.io/timelinejs-template/embed.html" width='100%' height='600' frameborder='0'></iframe>`
