### ISSUE TITLE
Request for second view of timeline JSON's - old school tabular.

### ISSUE THREAD

**Issue by paul-hammant** [thecdil/timelinejs-template#13]
Some who have weighed in on http://its-airborne.org/ have asked for a second representation of the same timeline data:  regular tables.

That's be a different page but consuming the same `/media/` resource.  Timelines are one thing, but some non-techniocal perusers want to be able to quickly see whether something is in there or not. Perhaps with find-in-page instead of clicking Next> a bunch of times to move the timeline.

**Comment by evanwill** [comment]
@paul-hammant not sure if it would be in scope of this template (as you know I haven't had a chance to do anything with it for like a year...), but pretty easy to add to a site. I use [DataTables](https://datatables.net/) in other projects, which adds search, sort, and export, etc. If you are using the CSV option, Jekyll can easily generate a variety of different data outputs from the same source to be consumed by stuff other than TimelineJS. 

You could:

- add the data to the page as HTML and let DataTables initiate on that table
- create some JSON that DataTables can consume (this is better for large sets)
- write some JS that parses the timelinejs json to provide to DataTables (which would support external json data sources)

For example, see this [collectionbuilder-gh table page](https://collectionbuilder.github.io/collectionbuilder-gh/data.html), which is generated from this [js include](https://github.com/CollectionBuilder/collectionbuilder-gh/blob/main/_includes/js/table-js.html).
Another example, I parse a google sheet spreadsheet and create a table in this template, https://github.com/evanwill/table-sheet-test

**Comment by paul-hammant** [comment]
Thanks - was fairly easy - https://github.com/its-airborne/timelines-site/blob/main/pages/historical-list.md

**Comment by evanwill** [comment]
If you want to clean it up a bit, you can use the "custom foot" option: 

basically move the JS bit into an include, such as "_includes/historic-table.html", then on the markdown stub, use front matter `foot: historic-table.html`. On page build, this will put your custom JS at the bottom of the page, after the template's JQuery and bootstrap is loaded (so you don't have to load jquery twice), making things a bit more efficient on your site.
