### ISSUE TITLE
Load assets from CDN ?

### ISSUE THREAD

**Issue by paul-hammant** [thecdil/timelinejs-template#4]
I mean timeline-min.js in particular but others too.

Note too: timeline.js has the same contents as timeline-min.js in this repo.

**Comment by evanwill** [comment]
@paul-hammant the idea of the template is to be fully self-contained package, not relying on 3rd party services and usable offline, so CDN aren't a good choice for this context. You could easily swap out the css and js in the _includes/template/head.html and foot.html if seems important for your usecase

**Comment by paul-hammant** [comment]
Cool. 

But in the documentation, a note for the person using the template as to how **they could if they wanted to**, and an assurance that "it works" -

![image](https://user-images.githubusercontent.com/82182/100721070-c65d4d80-33b6-11eb-93ad-53d640a53fc4.png)

That and `git rm  assets/lib/timeline3`
